version: "3.7"
services:
  mongodb:
    image: mongo:6.0.6
    container_name: 'mongo'
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services
  rabbitmq:
    image: rabbitmq:3.11.17-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=username"
      - "RABBITMQ_DEFAULT_PASS=password"
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services
  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services
  orderservice:
    build: src/order-service
    container_name: 'orderservice'
    restart: always
    ports:
      - 3000:3000
    environment:
      - ORDER_QUEUE_PROTOCOL=amqp
      - ORDER_QUEUE_HOSTNAME=rabbitmq
      - ORDER_QUEUE_PORT=5672
      - ORDER_QUEUE_USERNAME=username
      - ORDER_QUEUE_PASSWORD=password
    networks:
      - backend_services
    depends_on:
      rabbitmq:
        condition: service_healthy
  makelineservice:
    build: src/makeline-service
    container_name: 'makelineservice'
    restart: always
    ports:
      - 3001:3001
    environment:
      - RABBITMQ_CONNECTION_STRING=amqp://username:password@rabbitmq:5672/
      - RABBITMQ_QUEUE_NAME=orders
      - REDIS_CONNECTION_STRING=redis://redis:6379/0
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
      - MONGO_DATABASE_NAME=orderdb
      - MONGO_COLLECTION_NAME=orders
    networks:
      - backend_services
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  storefront:
    build: src/store-front
    container_name: 'storefront'
    restart: always
    ports:
      - 8080:8080
    environment:
      - ORDER_SERVICE_URL=http://orderservice:3000/
    networks:
      - backend_services
    depends_on:
      - orderservice
  virtualworker:
    build: src/virtual-worker
    container_name: 'virtualworker'
    restart: always
    ports:
      - 4001:4001
    environment:
      - FASTIFY_PORT=4001
      - ORDER_QUEUE_PROTOCOL=amqp
      - ORDER_QUEUE_HOSTNAME=rabbitmq
      - ORDER_QUEUE_PORT=5672
      - ORDER_QUEUE_USERNAME=username
      - ORDER_QUEUE_PASSWORD=password
      - ORDER_DB_URL=mongodb://mongo:27017/orderdb
    networks:
      - backend_services
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
networks:
  backend_services:
    driver: bridge