name: package-ai-service

on:
  push:
    branches:
      - 'main'
    paths:
      - 'ai-service/**'

  workflow_dispatch:

jobs:
  publish-container-image:
    
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        id: variables
        run: |
          echo "PROJECT=ai-service" >> "$GITHUB_OUTPUT"
          echo ${{ steps.main.outputs.PROJECT }}
          echo "action_state=yellow" >> "$GITHUB_ENV"
          echo "${{ env.action_state }}" 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Testing variables
        id: test-variables
        run: |
          echo ${{ steps.main.outputs.PROJECT }}
          echo "${{ env.action_state }}"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}        
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/ai-service
          file: src/ai-service/Dockerfile
          push: true
          tags: |
            ${{ needs.set-env.outputs.repository }}/${{ needs.set-env.outputs.image }}:latest
            ${{ needs.set-env.outputs.repository }}/${{ needs.set-env.outputs.image }}:${{ needs.set-env.outputs.version }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ needs.set-env.outputs.created }}
            org.opencontainers.image.revision=${{ needs.set-env.outputs.version }}